### ISSUE TITLE
Clean up directory naming

### ISSUE THREAD

**Issue by gingerwizard** [elastic/examples#106]
@asawariS can we move away from this "ElasticStack" prefix and do a restructuring. I'd rather do this now rather whilst the repo is still moderate in size.

**Comment by asawariS** [comment]
@gingerwizard agreed. Besides dropping "ElasticStack", I would vote for dropping other product names -- noticed a few kibana, packetbeat and shield in the naming

**Comment by gingerwizard** [comment]
@asawariS can you describe the prefered structure?

**Comment by gingerwizard** [comment]
https://github.com/elastic/examples/issues/148
