### ISSUE TITLE
NYC accident visualization

### ISSUE THREAD

**Issue by selvendran-varathan** [elastic/examples#117]
Hi,

Thanks for the effort in sharing the ELK examples. I have just tried NYC accidents Kibana visualization. I was able to import the data to ES and when tried to visualize the dashboard, getting error. Attached the screenshot for reference.

Thanks,
Selva
<img width="1444" alt="screen shot 2017-01-30 at 10 48 22 pm" src="https://cloud.githubusercontent.com/assets/15740189/22454984/7a406f54-e73e-11e6-90c0-f4b0d6fbad39.png">

**Comment by gingerwizard** [comment]
Fixed in https://github.com/elastic/examples/issues/148
