### ISSUE TITLE
Add Content-Type header to examples where applicable

### ISSUE THREAD

**Issue by eskibars** [elastic/examples#118]
As a result of elastic/elasticsearch#22691, we'll need to make changes to examples here. This looks like it affects under [20 examples](https://github.com/elastic/examples/search?q=curl&type=Code&utf8=%E2%9C%93).

Starting in 6.0, any curl command to Elasticsearch containing content (things with curly braces) will require a valid content-type. As a result, many existing curl commands won't work. Starting in 5.3, we're going to deprecate requests without this header. Though they'll continue to work in 5.x, we obviously don't want people copying/pasting curl commands from our examples repo that won't work in 6.x and we don't want to set them up for failure if they're starting now, so the change would be good to make regardless. The change is relatively simple on an individual basis: we simply need to add -H "Content-Type: application/json" to the curl command.

**Comment by gingerwizard** [comment]
https://github.com/elastic/examples/issues/148 addressed here
