### ISSUE TITLE
Twitter: field paramter error

### ISSUE THREAD

**Issue by kirkins** [elastic/examples#119]
I'm following the twitter example and it works up to the last step where I import` twitter_kibana.json` and try to view the results:

> 
> 2 Saved "field" parameter is now invalid. Please select a new field.
> 
> 5 Visualize: "field" is a required parameter

**Comment by gingerwizard** [comment]
Apologies for the late reply. The repo has undergone several fixes since this issue. I just tested this example end to end on 5.6.3 Kibana + Elasticsearch + Logstash, and wasn't able to reproduce this issue.
