### ISSUE TITLE
Screenshot deleted from the earthquake example

### ISSUE THREAD

**Issue by kosho** [elastic/examples#121]
@asawariS It seems[ the screenshot](https://github.com/elastic/examples/blob/ea745b74585a78fbd5d77f797f0f6d69f107d8c4/ElasticStack_earthquakes/ncedc-earthquakes-screenshot.png) of the earthquake dashboard is deleted from the repo along with other [changes](https://github.com/elastic/examples/commit/ea745b74585a78fbd5d77f797f0f6d69f107d8c4). Is it intended?

**Comment by asawariS** [comment]
thanks for pointing it out @kosho. will look into it.

**Comment by asawariS** [comment]
fixed.
