### ISSUE TITLE
Get  NGINX Logs error

### ISSUE THREAD

**Issue by smallfish01** [elastic/examples#122]
Hi,
I followed the document "Getting Started with Elastic Stack for NGINX Logs" and the url is https://github.com/elastic/examples/tree/master/ElasticStack_NGINX, I configured Nginx on my ELK server as this document, when I access http://elk.abc.com/nginx_elastic_stack_example/_count and I got the error:
{"statusCode":404,"error":"Not Found"}

I don't know why.

Could you please have a look?

**Comment by gingerwizard** [comment]
@smallfish01 this seems to be an issue with your infrastructure. Are you even able to access ES on http://<host>:<port>

?

**Comment by gingerwizard** [comment]
no response
