### ISSUE TITLE
exception=>"Twitter::Error::Unauthorized"

### ISSUE THREAD

**Issue by Sujeet1604** [elastic/examples#124]
21:25:24.497 [[main]<twitter] WARN  logstash.inputs.twitter - Twitter client err
or {:message=>"", :exception=>"Twitter::Error::Unauthorized", :backtrace=>["C:/U
sers/sujeet.kumar/Pictures/ELK_5.3/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/t
witter-5.15.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'", "o
rg/ruby_http_parser/RubyHttpParser.java:370:in `<<'", "C:/Users/sujeet.kumar/Pic
tures/ELK_5.3/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twi
tter/streaming/response.rb:16:in `<<'", "C:/Users/sujeet.kumar/Pictures/ELK_5.3/
logstash-5.3.0/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.3/lib/log
stash/inputs/twitter/patches.rb:31:in `stream'", "C:/Users/sujeet.kumar/Pictures
/ELK_5.3/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.
3/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "C:/Users/sujeet.kuma
r/Pictures/ELK_5.3/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/li
b/twitter/streaming/client.rb:37:in `filter'", "C:/Users/sujeet.kumar/Pictures/E
LK_5.3/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.3/
lib/logstash/inputs/twitter.rb:138:in `run'", "C:/Users/sujeet.kumar/Pictures/EL
K_5.3/logstash-5.3.0/logstash-core/lib/logstash/pipeline.rb:425:in `inputworker'
", "C:/Users/sujeet.kumar/Pictures/ELK_5.3/logstash-5.3.0/logstash-core/lib/logs
tash/pipeline.rb:419:in `start_input'"], :options=>nil}

**Comment by gingerwizard** [comment]
Apologies for the late reply. This looks like your twitter app credentials are incorrect. Did you compelete the secret key etc?

**Comment by gingerwizard** [comment]
Closing no reply.

**Comment by rmahlatse** [comment]
I got the same error, after stopping logstash to restart computer, when i restarted logstash it gave this error
