### ISSUE TITLE
Examples/recipes.css is 0 Bytes

### ISSUE THREAD

**Issue by pdc-kaminaga** [elastic/examples#132]
I downloaded elastic/examples (https://github.com/elastic/examples)
But examples/elasticsearch_app_java_recipe_search/src/main/webapp/css/recipes.css is 0 bytes.
Where can I download recipes.css?

**Comment by gingerwizard** [comment]
@daragies i see you committed this code. Is this file intentionally empty? If so, can we remove to avoid confusion.

**Comment by pdc-kaminaga** [comment]
I understood my mistake.
I can not display details in Firefox.
I can display details in Chrome.
(recipes.css is 0 bytes) was not the cause.
