### ISSUE TITLE
hi,how can i fix the nginx json error with logstash?

### ISSUE THREAD

**Issue by samuelzengcn** [elastic/examples#135]
NGINX uses \xXX to encode some characters. The resulting "JSON" string is not valid (the JSON standard specifies \u00XX) and in Logstash you will get a json parse error for the invalid JSON string. It only happens when any variables e.g. $http_user_agent contain characters that NGINX will escape e.g. backslash or reverse solidus.

**Comment by gingerwizard** [comment]
@samuelzengcn see https://github.com/elastic/examples/issues/130
