### ISSUE TITLE
Images for examples

### ISSUE THREAD

**Issue by asawariS** [elastic/examples#14]
<img width="1253" alt="donorschoose_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/10270320/679104f0-6aa2-11e5-869f-652e1bcfe0c1.png">

![nyc_collision_dashboard](https://cloud.githubusercontent.com/assets/5269751/10008565/f548dc28-6084-11e5-9956-b29c2ca043ee.png)
<img width="1254" alt="usfec_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/9821738/0e4c9276-5871-11e5-9348-99074cab1aa6.png">
<img width="1272" alt="nginx_json_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/9672317/7c5b763e-524e-11e5-949f-b8dad81bce8f.png">

<img width="1272" alt="nginx_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/9672326/8626f33c-524e-11e5-824e-728ce97ce061.png">

<img width="1221" alt="twitter_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/9672393/070e94dc-524f-11e5-9e80-3101e2cf1573.png">

<img width="1271" alt="apache_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/9672401/19fe21de-524f-11e5-86a6-49e76636c79a.png">

<img width="1251" alt="kibana_exercise_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/11385430/a0e76804-92cd-11e5-99a7-0450c87ca375.png">
<img width="1251" alt="kibana_nutrition_dashboard" src="https://cloud.githubusercontent.com/assets/5269751/11385436/a542ed56-92cd-11e5-9f0a-8a243a55f054.png">
![restaurants_kibana](https://cloud.githubusercontent.com/assets/5269751/14194018/dcebcb2e-f75e-11e5-924a-673731d89743.jpg)

**Comment by jairagoo** [comment]
J

Minimum I m

Jjn
N
Nn
An O
n

OK

~Jai

**Comment by gingerwizard** [comment]
![movie_lens_example_graph](https://cloud.githubusercontent.com/assets/12695796/20490466/072dea1a-b006-11e6-924d-d4f7c55a5aa5.jpg)

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/20490545/47276e7a-b006-11e6-988a-4e0d1054eee2.png)

**Comment by gingerwizard** [comment]
![movie_lens_total_reviews_by_date](https://cloud.githubusercontent.com/assets/12695796/20490652/99acb592-b006-11e6-90bc-b0b018afb3e0.png)

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/21648199/0078db7e-d295-11e6-8a3c-357074a4e12a.png)

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/21771118/08339dd0-d67e-11e6-9fdf-9473ddd3e1f6.png)

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/24197080/168a40fc-0ef8-11e7-9c32-3182dd23c76c.png)

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/24197092/1eb5f82a-0ef8-11e7-9cdf-6c55e144f9b5.png)

**Comment by smallfish01** [comment]
Very beautiful graph, could you please share your steps?

Thank you!

**Comment by asawariS** [comment]
@smallfish01 this issue just collects dashboard images covered in the [various example ReadMe in the repo](https://github.com/elastic/examples). You can grab the steps for recreating the dashboard from the appropriate folder. Hope that helps.

**Comment by gingerwizard** [comment]
![image](https://cloud.githubusercontent.com/assets/12695796/26511381/af159f94-4259-11e7-9719-4fcc2897f2c7.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27012292-e7bd5e6e-4ec4-11e7-9d8d-08d90b67cbf3.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27547566-5a5e0dfe-5a8e-11e7-9649-fb9758dd941a.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27547794-f4714b9a-5a8e-11e7-8f86-ccfe940a811c.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27696543-d1d895ae-5ce9-11e7-825e-dda28cf00eeb.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27917014-adcc505a-6262-11e7-87c1-be24cb8c05fa.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27922049-b0dc3742-6271-11e7-9c52-b2041d7b2bf1.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/27926793-8f104b84-6281-11e7-8a74-521613280290.png)

**Comment by asawariS** [comment]
![kibana_nutrition_dashboard](https://user-images.githubusercontent.com/5269751/28243536-d18cea8c-6982-11e7-9073-6747c81399b5.jpg)
![kibana_exercise_dashboard](https://user-images.githubusercontent.com/5269751/28243535-d18cdda8-6982-11e7-901d-d60db62ec478.jpg)

**Comment by asawariS** [comment]
![donorschoose_dashboard](https://user-images.githubusercontent.com/5269751/28243545-367f211c-6983-11e7-8196-56adf0ccd52a.jpg)
