### ISSUE TITLE
Ingest w/o Logstash

### ISSUE THREAD

**Issue by bsullins** [elastic/examples#140]
Is it possible to use the following method to ingest these logs? I've manually created the index in ES and tried this but am getting errors related to the filetype. I'm running Mac OS Sierra.

```curl -H 'Content-Type: application/x-ndjson' -XPOST 'localhost:9200/_bulk?pretty' --data-binary @apache_logs```

Do I have the wrong content type perhaps?

**Comment by joshuar** [comment]
@bsullins it's probably better to use the filbeat apache module for this, see the example for nginx logs here:

https://www.elastic.co/guide/en/beats/filebeat/current/_tutorial.html

We need to add this as an example :)

**Comment by gingerwizard** [comment]
The above solution of using curl would require the logs to be preprocessed in json. This somewhat negates the purpose of the example.

We are going to update the examples to use filebeat however.

**Comment by gingerwizard** [comment]
I have a PR for this coming as part of a larger refactor.

**Comment by gingerwizard** [comment]
Will be addressed under https://github.com/elastic/examples/issues/148
