### ISSUE TITLE
Refresh Docker Examples

### ISSUE THREAD

**Issue by gingerwizard** [elastic/examples#147]
The docker examples use out of date images that have subsequently been replaced by an official versions.  

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
https://www.elastic.co/guide/en/kibana/current/_configuring_kibana_on_docker.html
https://www.elastic.co/guide/en/logstash/current/docker.html
https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html

The proposal is to use docker compose to produce an Elastic Stack example that ingests an example log file using two archiectures:

1. Filebeat->Elasticsearch<-Kibana
1. Filebeat->Logstash->Elasticsearch<-Kibana

We can provide more complex examples over time.

@rudijs given your initial contribution would you be interested in assisting?

@dliappis @ESamir  do we have examples for the above already?

@asawariS

**Comment by rudijs** [comment]
@gingerwizard Hi Dale, yep I'm interested to help out. Starting the end of next week I'll have some time to follow up on this. I'll clone and create a branch to get started.

**Comment by gingerwizard** [comment]
Hi @rudijs we have actually started an effort [here](https://github.com/gingerwizard/examples/tree/master/Miscellaneous/docker/full_stack_example).  This PR will deliver a compose file that starts up a full stack with beats,LS,ES and kibana containers + supporting apache, nginix and mysql.

The latter will act as datasources. The file also installs also beats and x-pack thus giving a full stack experience. I would appreciate a review if you have time when i make the PR.

**Comment by gingerwizard** [comment]
https://github.com/elastic/examples/pull/165
