### ISSUE TITLE
Load watch_history_dashboard.json failed

### ISSUE THREAD

**Issue by KeithTt** [elastic/examples#154]
ELK version: 5.4.1

I followed this guide:
https://github.com/elastic/examples/tree/master/Alerting/watcher_dashboard

When I import the json file, it always report a error:

`Saved Objects: The file could not be processed.`

**Comment by tylersmalley** [comment]
This issue was cross-posted on Discus: https://discuss.elastic.co/t/load-json-file-failed-the-file-could-not-be-processed/94107/2

I verified the ability to import the saved objects and am closing this issue.
