### ISSUE TITLE
Add examples for using watches against Reporting functionality

### ISSUE THREAD

**Issue by geekpete** [elastic/examples#160]
Would be good to get some reporting examples added.

**Comment by gingerwizard** [comment]
This should be fairly straightforward. Maybe even a blog here @asawariS @jamiesmith

**Comment by geekpete** [comment]
Would these docs satisfy this issue allowing it to be closed now I wonder or are there more detailed examples that might be useful?
https://www.elastic.co/guide/en/kibana/7.11/automating-report-generation.html#_use_watcher

Any additional Kibana Alerting examples that also might be included in this context?
