### ISSUE TITLE
Machine Learning example Lab 3 type field inconcisteny

### ISSUE THREAD

**Issue by walterra** [elastic/examples#164]
The mapping for the index for Machine Learning example Lab 3 (user activity) defines `metric` as the type here: https://github.com/elastic/examples/blob/master/Machine%20Learning/Getting%20Started%20Examples/user_activity/ingest-data.sh#L23

However, the JSON data referenced in the README file (https://github.com/elastic/examples/blob/master/Machine%20Learning/Getting%20Started%20Examples/user_activity/README.md) for the `wget` command uses `log` as the type.

So the `metric` mapping will not be used when ingesting the data. Furthermore, with upcoming versions of Elasticsearch, this example will not work anymore, because support for multiple mapping types within an index will be deprecated.

To fix this, the type fields need to match both in the ingest script as well as the JSON data.

**Comment by asawariS** [comment]
thanks @walterra for pointing it out -- will fix asap.

**Comment by gingerwizard** [comment]
@asawariS if you make a PR just merge straight away.

**Comment by gingerwizard** [comment]
I believe the video uses log as does the data sample. The simpler change here is the mapping. Will change. Thanks @walterra

**Comment by gingerwizard** [comment]
Closed by https://github.com/elastic/examples/pull/180
