### ISSUE TITLE
Provided Grok expressions do not match field value

### ISSUE THREAD

**Issue by shazChaudhry** [elastic/examples#166]
Trying to work with this example: https://github.com/elastic/examples/tree/master/Common%20Data%20Formats/apache_logs

I have downloaded and ingested 'apache_logs' sample data into Elasticsearch 5.5.1 using Filebeat 5.5.1. 

It appears that every single message in Kibana has the same error. Here is one example:
{
  "_index": "filebeat-2017.08.31",
  "_type": "doc",
  "_id": "AV42CkhKqm6o0f27MfTI",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2017-08-31T02:06:31.483Z",
    "offset": 2367795,
    "beat": {
      "hostname": "d05e478cd89b",
      "name": "d05e478cd89b",
      "version": "5.5.1"
    },
    "input_type": "log",
    "source": "/usr/share/filebeat/apache_logs/apache_logs",
    "fileset": {
      "module": "apache2",
      "name": "access"
    },
    "message": "63.140.98.80 - - [20/May/2015:21:05:50 +0000])\"",
    "type": "log",
    "error": "Provided Grok expressions do not match field value: [63.140.98.80 - - [20/May/2015:21:05:50 +0000])\\\"]"
  },
  "fields": {
    "@timestamp": [
      1504145191483
    ]
  },
  "sort": [
    1504145191483
  ]
}

I will be grateful for any suggestion how I can resolve this error.

**Comment by gingerwizard** [comment]
@shazChaudhry is this on windows by any chance?

**Comment by gingerwizard** [comment]
I'm able to reproduce this.   It impacts 14 documents out of 10,000 as illustrated by the query.

```
curl -XGET "http://localhost:9200/filebeat-*/_search" -H 'Content-Type: application/json' -d'
{
  "query": {
    "exists":{
      "field":"error"
    }
  }
}'
```
Unfortunately these show first -as they have no extracted date. The documents in the field are indeed invalid with respect to the Grok pattern - we should probably enhance the filebeat apache module to be more resilient @tsg Would we prefer to do best effort here or just fail? Example line,

`63.140.98.80 - - [20/May/2015:21:05:58 +0000])"``

Sample is available here

`wget https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs`

**Comment by gingerwizard** [comment]
This doesn't require resolution - it doesn't impact the function of the example. These lines are simply poorly formatted. I'll fix the data at source and push a fix now.

**Comment by gingerwizard** [comment]
Fixed https://github.com/elastic/examples/pull/181
