### ISSUE TITLE
full_stack_example - OSX - packetbeat doesn't capture host traffic

### ISSUE THREAD

**Issue by mike-mosher** [elastic/examples#168]
README states that packetbeat is capturing host traffic, and not traffic between the containers.  However, when I do a data table visualization of the http.request.headers.host field, I get the following:

http.request.headers.host: Descending | Count
elasticsearch:9200 | 4,011
localhost:9200 | 2,257
localhost:5601 | 262
apache2 | 113
nginx | 113
kibana:5601 | 1

It doesn't seem to be capturing any traffic from the host.  Anything I need to change in the configuration / docker / host to get this to work?

**Comment by gingerwizard** [comment]
I think the README isn't clear unfortunately - i'll clarify. Currently Packetbeat only sees the VMs adapter which is running docker.  The native host adapter isn't visible. We're exploring ways to do this reliably and will update the image accordingly.

**Comment by gingerwizard** [comment]
I'm going to clarify this in the docs - this issue is specific to windows and osx, where docker runs on a VM.  Otherwise this should capture host traffic on linux

**Comment by gingerwizard** [comment]
https://github.com/elastic/examples/pull/182
