### ISSUE TITLE
ML/Tweets example: wrong URL to download sample data

### ISSUE THREAD

**Issue by walterra** [elastic/examples#169]
The command in `EXAMPLE.md` (https://github.com/elastic/examples/blob/master/Machine%20Learning/Business%20Metrics%20Recipes/twitter_trends/EXAMPLE.md#example-1---static-dataset) to download the sample tweets didn't work for me:

```
curl -O https://github.com/elastic/examples/tree/master/Machine%20Learning/Business%20metrics%20recipes/twitter_tends/data/tweets.csv
```

It works using the following URL:

```
 curl -O https://raw.githubusercontent.com/elastic/examples/master/Machine%20Learning/Business%20Metrics%20Recipes/twitter_trends/data/tweets.csv
```

**Comment by gingerwizard** [comment]
Thanks well spotted ill correct.

**Comment by gingerwizard** [comment]
Fixed thanks again @walterra
