### ISSUE TITLE
Update to examples for [E - 2.0.0beta2; L - 2.0.0beta1; K - 4.2.0-beta2]

### ISSUE THREAD

**Issue by vijaygharge** [elastic/examples#17]
First of all thanks for great examples as kick-start for newbies like me :-)

Few updates in examples : 

apache_template.json => [ "path": "full",] option is deprecated https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/94

apache_logstash.conf =>
1. protocol => default elasticsearch output protocol set to http [https://www.elastic.co/guide/en/logstash/2.0/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch"
2. host => host configuration parameter renamed to hosts https://github.com/elastic/logstash/blob/master/CHANGELOG.md
3. cluster => cluster configuration parameter disappeared completely without any trace

**Comment by asawariS** [comment]
Hi @vijaygharge 

Glad the examples we helpful. And a big thanks for the feedback! 

Our thought is to only update examples for major GA releases. The examples are tested in the most current GA release, and the tested versions are clearly marked in the ReadMe. We will be sure to update the examples once 2.0 GA is out. Thanks for pointers - they will definitely help during the update process :)
Keep the feedback rolling!!
