### ISSUE TITLE
nyc_restaurants, can't load visualizations.

### ISSUE THREAD

**Issue by pomarc** [elastic/examples#176]
ES 5.6.2
Kibana 5.6.2
on linux ubuntu

when importing the restaurants_kibana.json file, I get a lot of errors like:

 
`Saved Objects: Importing DOHMH: Violation Details (DOHMH:-Violation-Details) failed: Could not locate that index-pattern (id: nyc_restaurants), click here to re-create it`

```
Error: Importing DOHMH: Violation Details (DOHMH:-Violation-Details) failed: Could not locate that index-pattern (id: nyc_restaurants), [click here to re-create it](#/management/kibana/index?id=nyc_restaurants&name=)
KbnError@http://localhost:5601/bundles/commons.bundle.js?v=15543:83:18358
SavedObjectNotFound@http://localhost:5601/bundles/commons.bundle.js?v=15543:83:23444
updateFromElasticSearch@http://localhost:5601/bundles/kibana.bundle.js?v=15543:27:5982
value/<@http://localhost:5601/bundles/kibana.bundle.js?v=15543:27:10194
processQueue@http://localhost:5601/bundles/commons.bundle.js?v=15543:38:23621
scheduleProcessQueue/<@http://localhost:5601/bundles/commons.bundle.js?v=15543:38:23888
$eval@http://localhost:5601/bundles/commons.bundle.js?v=15543:39:4607
$digest@http://localhost:5601/bundles/commons.bundle.js?v=15543:39:2343
$apply@http://localhost:5601/bundles/commons.bundle.js?v=15543:39:5026
done@http://localhost:5601/bundles/commons.bundle.js?v=15543:37:25016
completeRequest@http://localhost:5601/bundles/commons.bundle.js?v=15543:37:28702
createHttpBackend/</xhr.onload@http://localhost:5601/bundles/commons.bundle.js?v=15543:37:29634
```

 
 
but I am quite confident that nyc_restaurants is present, since:
 
```
`curl -H "Content-Type: application/json" -XGET localhost:9200/nyc_restaurants/_count -d '{"query": {                       
"match_all": {}
}
}'
```

gives
 
{"count":473039,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0}}`

this, in tun, breaks the loaded dashboard with a lot of missing visualization error.
any clue?
thanks

**Comment by LucaWintergerst** [comment]
Hello @pomarc , 
it looks like you skipped the step of creating the index pattern.

> Connect Kibana to the nyc_restaurants index in Elasticsearch
Click the Management tab >> Index Patterns tab >> Create New. Specify nyc_restaurants as the index pattern name, select Inspection_Date as the Time-field name, and click Create to define the index pattern. (Leave the Use event times to create index names box unchecked)

After doing so, try the import again.

Please let me know if you have any other questions, I will close this for now.
Luca
