### ISSUE TITLE
Docker ELK Quickstart: Elasticsearch, Logstash, Kibana

### ISSUE THREAD

**Issue by rudijs** [elastic/examples#18]
Hi,

I'm using the ELK stack with Docker and I think adding some Install and setup steps would be helpful for those also interested to use Docker.

I've actually gone ahead and done this already and posted it to my blog.

If you like, we could use that content (modified anywhere you deem appropriate) and add it here.

I'd be happy to put the content together and create a pull request - or not, it's up to you really.

The content I've used in my blog is just a single markdown file and 3 images.

Here's a link to the blog post HTML you can review:

http://rudijs.github.io/2015-10/docker-elk-quickstart/

Here's a link to the markdown source

https://raw.githubusercontent.com/rudijs/rudijs.github.io/master/_posts/2015-10-05-docker-elk-quickstart.markdown

There's some jekyll tags that'd be stripped out, perhaps just the content from Overview to Summary could be used here.

Anyways, let me know if you're interested and I'll help to prepare it.

Cheers.

**Comment by asawariS** [comment]
Hi there @rudijs, 

We would love to add this example to the repo. Please create the content and submit a pull request for review. We can iterate as needed from there. Looking forward to seeing your submission. 

Asawari

**Comment by rudijs** [comment]
@asawariS OK great .. pull request sent.

I'll close this issue for now, any further discussion can be done in the pull request.

Thanks.
