### ISSUE TITLE
HOW TO DEBUG ISSUES LOGTASH OR ELASTIC SEARCH AND KIBANA

### ISSUE THREAD

**Issue by narengol** [elastic/examples#231]
HOW TO DEBUG ISSUES  IN LOGTASH OR ELASTIC SEARCH AND KIBANA IN THIS CLUSTER.
from the docker servers.

**Comment by aravindputrevu** [comment]
Hi @narengol ,

Thanks for creating a issue. However, [Discuss](https://discuss.elastic.co) is the best place to ask such questions. It is our technical forum. Please make sure that you add the problem statement and error that you are facing. 

Closing the issue here..
