### ISSUE TITLE
https://github.com/elastic/examples/tree/master/ELK_nginx-json

### ISSUE THREAD

**Issue by kunalvjti** [elastic/examples#24]
For https://github.com/elastic/examples/tree/master/ELK_nginx-json, the highlighted text below in README should be nginx_json_logstash.conf instead of apache_logstash.conf

Note: Included nginx_json_logstash.conf configuration file assumes that you are running Elasticsearch on the same host as Logstash and have not changed the defaults. Modify the host and cluster settings in the output { elasticsearch { ... } } section of **apache_logstash.conf**, if needed.

**Comment by asawariS** [comment]
@kunalvjti good catch. Thanks. Fixed ReadMe.
