### ISSUE TITLE
Canvas AMA Json Templates Fail

### ISSUE THREAD

**Issue by packet-rat** [elastic/examples#242]
The Canvas AMA templates fail.  The instructions and bulk load show the index as amaresponses.  

The Canvas widgets reference "responses" which of course fails:

```
{escount index="responses" q="business_group:Engineering"}
```

Changing all references from "responses"  to "amaresponses"  fixes the issue:

```
{escount index="amaresponses" q="business_group:Engineering"}
```

**Comment by jamiesmith** [comment]
Thanks for pointing that out, fixed!

**Comment by packet-rat** [comment]
Thanks for the quick response.  There are three more errors that I've not been able to resolve on my own. I see refrences in other places to these errors but no solutions.

(1) Conversations Stopwatch:
```
{
  "error": {
    "message": "[esdocs] > [sql_illegal_argument_exception] Arrays (returned by [topics]) are not supported"
  }
}
```
(2) Use cases:
```
{
  "error": {
    "message": "[timelion] > unable to verify the first certificate"
  }
}
```
(3) Visiti Times
```
{
  "error": {
    "message": "[timelion] > unable to verify the first certificate"
  }
}
```

**Comment by packet-rat** [comment]
![2018-12-01_12-52-05](https://user-images.githubusercontent.com/3220193/49331239-ecea1300-f567-11e8-8727-3d6b2c267f77.png)
