### ISSUE TITLE
Add Elk2 Out of the box demo

### ISSUE THREAD

**Issue by salyh** [elastic/examples#26]
https://github.com/salyh/elk2-out-of-the-box-demo

**Comment by asawariS** [comment]
Hi @salyh, 

Thanks for the submission. As you might have noticed, we already have a [NYC traffic accidents](https://github.com/elastic/examples/tree/master/ELK_nyc_traffic_accidents) example in the current repo.  Except for the vagrant / docker piece, how would this submission be different from that example?

Thanks!
Asawari

**Comment by asawariS** [comment]
@salyh closing this out for now. Feel free to reopen.
