### ISSUE TITLE
older k8s apiVersions not supported 

### ISSUE THREAD

**Issue by acelinkio** [elastic/examples#307]
`apiVersion: extensions/v1beta1`  is not supported in newer versions of k8s.  This requires change to `apps/v1` and a small change to selector.  

Found this issue while following the https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/ tutorial.

**Comment by gnumoksha** [comment]
Relates to https://github.com/kubernetes/website/issues/23483

**Comment by DanRoscigno** [comment]
Thanks @AcelinkIT and @gnumoksha I will have a look at it.
