### ISSUE TITLE
beats-k8s-send-anywhere: download.txt does not exist

### ISSUE THREAD

**Issue by gnumoksha** [elastic/examples#349]
[Here](https://github.com/elastic/examples/tree/master/beats-k8s-send-anywhere#clone-the-yaml-files) there is a reference to a file called `download.txt` that does not exist.

**Comment by DanRoscigno** [comment]
Thanks @gnumoksha , please clone the repo instead of using download.txt.  I will update the instructions.  Thanks for letting us know!

**Comment by DanRoscigno** [comment]
@gnumoksha I am updating this example at the moment, if you are using a recent version of k8s the manifesto files will fail as we have not updated them since the DaemonSet and Deployment beta specifications were retired.  I should be finished testing in an hour and will submit a PR.
