### ISSUE TITLE
dns-tunnel-iodine.pcap corrupt

### ISSUE THREAD

**Issue by awick** [elastic/examples#39]
editcap, tcpdump and wireshark don't seem to like dns-tunnel-iodine.pcap is it corrupt, or some windows/mac binary file issue?

**Comment by andrewkroh** [comment]
Not sure what happened there. I found the original on my machine and updated it.

MD5 (dns-tunnel-iodine.pcap) = 83056218214cf8c30b583ee1ee6c5a91
