### ISSUE TITLE
NYC collision data example

### ISSUE THREAD

**Issue by rains555** [elastic/examples#41]
Hi, 
I'm a newbie, I'm running the nyc collision data example, and have elasic and kibana up and running, data and examples files are downloaded.

I'm getting an error with step 1. ingest data into elasticsearch using logstash:
cat nyc_collision_data.csv | d:/downloads/logstash-2.3.0/bin/logstash -f nyc_collision_logstash.conf

I'm using windows command prompt, and the message I receive is:  'cat' is not recognized as an internal or external command, operable program or batch file.  

how do i get past this error?
thx,
rains

![image](https://cloud.githubusercontent.com/assets/18313655/14327863/442a4b88-fc02-11e5-9fb8-2ae5d5c9ae53.png)

**Comment by rains555** [comment]
also tried these two commands from different directory paths (1) from directory with dataset (2) other from logstash-2.3.0\bin with different error.

1
![image](https://cloud.githubusercontent.com/assets/18313655/14328106/43ec710e-fc03-11e5-9e94-d6a4d00d62b1.png)

2
![image](https://cloud.githubusercontent.com/assets/18313655/14328116/522569a6-fc03-11e5-8db6-b00580258f14.png)

**Comment by asawariS** [comment]
Hi. I assume you are on a Windows machine. cat is not a built-in command on Windows OS. Try this `type` instead of `cat` 

`type nyc_collision_data.csv | d:/downloads/logstash-2.3.0/bin/logstash -f nyc_collision_logstash.conf`

**Comment by rains555** [comment]
thanks for the quick response...I tried that but comes with a different error around the 'd:', so I removed it and received a different error.

![image](https://cloud.githubusercontent.com/assets/18313655/14328408/84bad1fc-fc04-11e5-82c7-98ef27e1584b.png)

![image](https://cloud.githubusercontent.com/assets/18313655/14328421/9888c11c-fc04-11e5-9f25-c058bbf10a75.png)

**Comment by asawariS** [comment]
what happens if you try: 
`d:/downloads/logstash-2.3.0/bin/logstash -e 'input { stdin { } } output { stdout {} }'`

**Comment by asawariS** [comment]
Actually try specifying the path with a \ instead of forward slash
`type nyc_collision_data.csv | d:\downloads\logstash-2.3.0\bin\logstash -f nyc_collision_logstash.conf`

**Comment by rains555** [comment]
tried that...same error.    should I be executing the command from a specific folder?  right now it's being executing from the same folder that contains the nyc_collision_data.csv.

![image](https://cloud.githubusercontent.com/assets/18313655/14330751/0a9f03b4-fc10-11e5-814b-14f9f74a953c.png)

**Comment by asawariS** [comment]
It's a different error from last time. If you see the first command - the error is "System cannot find the specified file" ... so it cannot find the location of either logstash binary or the `nyc_collision_logstash.conf` file. 

You are running this command from the `D:\Downloads\datasets` folder. Are  `nyc_collision_data.csv` and  `nyc_collision_logstash.conf` files both located in this folder. 

Also, can you confirm the location of the logstash install directory -- based on your command you should have `D:\downloads\logstash-2.3.0\bin` folder with a logstash binary in it

**Comment by rains555** [comment]
the files are located in d:\downloads\datasets\nycollision.  
![image](https://cloud.githubusercontent.com/assets/18313655/14331371/052f9be8-fc13-11e5-8d9c-e36a5d8f4713.png)

![image](https://cloud.githubusercontent.com/assets/18313655/14331400/20b92014-fc13-11e5-8fbb-e41ae655e6c9.png)


I ran the command from this path can received a different error that 'process tried writing to a non-existent pipe'.  elastic and kibana are running.

![image](https://cloud.githubusercontent.com/assets/18313655/14331357/f6a3fa1a-fc12-11e5-8935-7129a4021a8b.png)

**Comment by asawariS** [comment]
Could you please paste the last command you ran -- can't see it in the last image.

**Comment by rains555** [comment]
command:
![image](https://cloud.githubusercontent.com/assets/18313655/14331800/d623a612-fc14-11e5-876c-94912a445a22.png)

output:
![image](https://cloud.githubusercontent.com/assets/18313655/14331821/ec710ac2-fc14-11e5-8d44-baa274549ccb.png)

**Comment by asawariS** [comment]
Sorry about the back and forth on this -- What do you see when you run this: 

`D:\downloads\logstash-2.3.0\bin\logstash -e 'input { stdin { } } output { stdout {} }'`

**Comment by rains555** [comment]
this is what I see:

![image](https://cloud.githubusercontent.com/assets/18313655/14332305/ec781d6a-fc16-11e5-88a1-db013b8ca4c1.png)

**Comment by asawariS** [comment]
OK. Awesome. So Logstash is working. Let me try running the config on my machine with 2.3.0 and get back to you. Stay tuned!

**Comment by asawariS** [comment]
Can you try the same command again with the updated nyc_collision_logstash.conf file and let me know how it goes. 
https://github.com/elastic/examples/blob/master/ELK_nyc_traffic_accidents/nyc_collision_logstash.conf

**Comment by rains555** [comment]
high downloaded the file and tried the same command - error looks to be the same:
![image](https://cloud.githubusercontent.com/assets/18313655/14333797/823ab0b8-fc1e-11e5-900b-379b006c2556.png)


command:
![image](https://cloud.githubusercontent.com/assets/18313655/14333769/64945fd2-fc1e-11e5-8317-08152913d239.png)


output:
![image](https://cloud.githubusercontent.com/assets/18313655/14333760/5756d9f8-fc1e-11e5-8641-a77953686fc7.png)

**Comment by markwalkom** [comment]
What's `java -version` give you?

**Comment by rains555** [comment]
java version 1.8.0_77
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-bit Server VM <build 25.77-b03, mixed mode)

**Comment by asawariS** [comment]
Did you get this example to work @rains555

**Comment by rains555** [comment]
was not able to get this example to work.  any further ideas on how to get the data into Elastic?

**Comment by asawariS** [comment]
Did you try it with the newer version of Logstash, version 2.3.1 i.e.?

**Comment by rains555** [comment]
yes did try with logstash-2.3.1 and received the same error message..  

also tried changing the input parameters to read the data file in the config file and ran logstash with 'logstash -f nyc_collision_logstash.conf' but gave error messages.  
[nyc_collision_logstash.zip](https://github.com/elastic/examples/files/215108/nyc_collision_logstash.zip)



![image](https://cloud.githubusercontent.com/assets/18313655/14461803/2a075e82-0092-11e6-8959-2748a00de743.png)

**Comment by gingerwizard** [comment]
Can you please try on the latest 5.0 release?

**Comment by gingerwizard** [comment]
Closing as no response. Re-open if reproducible on latest.
