### ISSUE TITLE
twitter_elk_example

### ISSUE THREAD

**Issue by rains555** [elastic/examples#42]
Hi,
did not hear back on the nyc_collision example so tried the twitter_elk_example.  logstash pipeline was started by 4 workers but then received this error in teh screen shot.  any idea on how to resolve this error and get this example working?

![image](https://cloud.githubusercontent.com/assets/18313655/14362889/a056717a-fccf-11e5-86bf-5037f232e14a.png)

**Comment by asawariS** [comment]
Hey! Can you try the updated Logstash config files for Twitter example. Also, I will ask someone from the Logstash team to look at your NYC example problem. 

If the above doesn't work, could you do me a favor and upgrade Elasticsearch and Logstash to 2.3.1 which was released this morning. There was a bug in Logstash 2.3.0 that affected some configs and I want to rule that out as an issue.

**Comment by rains555** [comment]
sure I can try those suggestions.  do i need to change the directory path for this line in the logstash config file?
      template      => "./twitter_template.json"

**Comment by asawariS** [comment]
As long a the logstash config and template files are in the same folder, you should be fine with leaving that path as is.

**Comment by scanlonjts** [comment]
the twitter template is using causing errors with compress:true for _source

Freshly downloaded LogStash 231 and ES 231

**Comment by asawariS** [comment]
@scanlonjts Thanks for pointing out. Fixed and merged.

**Comment by rains555** [comment]
used the new logstash config file and added the path to he json template
template      => "D:/Downloads/datasets/twitter_elk_example/twitter_template.json".   there is progress - logstash pipeline is no longer stopping.  but i'm getting a continuous stream of errors

![image](https://cloud.githubusercontent.com/assets/18313655/14366747/50397c06-fce2-11e5-89e2-ff4274e813eb.png)

**Comment by asawariS** [comment]
@rains555 I just tweaked the template file as well -- se my last comment on this issue. You can either just grab the new one (or remove the ` "_source": { "compress": true },` line from your template file)

**Comment by scanlonjts** [comment]
I just updated- twitter example working!

**Comment by asawariS** [comment]
awesome @scanlonjts!

**Comment by rains555** [comment]
thanks asawariS and @scanlonjts 

twitter dashboard working...one pane is blank.  message says "Visualize: Zero or negative time interval not supported' -  makes sense but do you know where to fix it?

![image](https://cloud.githubusercontent.com/assets/18313655/14370227/24fdc4a8-fcfa-11e5-9544-b75a1ec33af2.png)

**Comment by asawariS** [comment]
@rains555 glad you got the twitter example working! What happens if you close the error? Does it reappear?

**Comment by rains555** [comment]
yes, it comes back if I close and then refresh the browser

**Comment by asawariS** [comment]
Weird. The histogram chart is trying to use 0ms for the interval -- hence the error. I am not seeing this on my end. 

Suggestion: Just delete and recreate the Tweet vs. Time plot and save the dashboard with the modified chart. That should fix it I think!

**Comment by rains555** [comment]
thanks - got it working
