### ISSUE TITLE
load JSON data 

### ISSUE THREAD

**Issue by rains555** [elastic/examples#43]
Hi I'm a EKL newbie and am trying to work through an issue.
I'm trying to load json file with below format.  I've created a mapping for it and followed the instructions at https://www.elastic.co/guide/en/kibana/current/getting-started.html#tutorial-load-dataset.  I get an error trying to load the JSON data into Elastic.  Note:  I was able to load the account data and shakespeare JSON data into Elastic.

**sample data**
  {
    "ID": "alpha1",
    "timestamp": "2016-01-29T22:00:17.334Z",
    "deviceID": "1",
    "deviceType": "watch1",
    "codec": "Z1",
    "notes": "blue watch"
  },
  {
      "ID": "alpha2",
      "timestamp": "2016-01-30T22:00:17.334Z",
      "deviceID": "2",
      "deviceType": "watch2",
      "codec": "Z2",
      "notes": "yellow watch"
  },
  {
      "ID": "alpha3",
      "timestamp": "2016-01-31T22:00:17.334Z",
      "deviceID": "3",
      "deviceType": "watch3",
      "codec": "Z3",
      "notes": "orage watch"
  },
  {
      "ID": "alpha4",
      "timestamp": "2016-02-02T22:00:17.334Z",
      "deviceID": "4",
      "deviceType": "watch4",
      "codec": "Z4",
      "notes": "red watch"
  }

**mapping**
curl -XPUT "localhost:9200/devices" -d"{""mappings"":{""_default_"":{""properties"":{""_id"":{""type"":""string"",""index"":""not_analyzed""},""created"":{""type"":""string"",""index"":""not_analyzed""},""serialNumber"":

{""type"":""integer""},""mtype"":{""type"":""string"",""index"":""not_analyzed""},""code"":{""type"":""string"",""index"":""not_analyzed""},""desc"":{""type"":""string"",""index"":""not_analyzed""}}}}}"

**data load command **
curl -XPOST "localhost:9200/devices/_bulk?pretty" --data-binary ""@d:\downloads\datasets\elastic\deviceList.json""

**error**
![image](https://cloud.githubusercontent.com/assets/18313655/14468155/8089d040-00ac-11e6-8489-d4552d12eb7a.png)

**Comment by asawariS** [comment]
@rains555 since this question is not quite related to any of the examples in the repo, I would recommend posting this and other generic Elastic Stack questions related to Elastic discuss forum. https://discuss.elastic.co/. The forums are monitored by Elastic engineers, as well as, by community users. So you are sure to get lot of great answers there. 

I will close this one out here for now.
