### ISSUE TITLE
output data so amazon s3 bucket

### ISSUE THREAD

**Issue by rains555** [elastic/examples#44]
Hi,
## I've tried a couple different ways to output data to an S3 bucket on Amazon.  I followed the documentation for output plug-ins to s3 but the function is not work.  Suggestions please?

filter { }

output {
  stdout {
   codec => dots
  }
    elasticsearch {
      hosts         => "http://localhost:9200"
      index         => "twitter"
      document_type => "tweets"
      template      => "D:/Downloads/datasets/iot/twitter_template.json"
      template_name => "twitter_example"
      template_overwrite => true
  }
   file {
      path => "D:/Downloads/datasets/twitter_iot/twitter.csv"
  }
   s3 {
     credentials => ["accessKeyID", "SecretKeyID"]
# access_key_id => "accessKeyID"
# secret_access_key => "SecretKeyID"

```
 region => "us-west-2"
 bucket => "s3://mybucket/path"
```

 }
}

**Comment by gingerwizard** [comment]
This should be really addressed through discuss.elastic.co
