### ISSUE TITLE
Example for tomcat logs

### ISSUE THREAD

**Issue by spahgnum** [elastic/examples#45]
Hi,

   The Apache example works like a charm!  I also want to know if you can provide an example for Tomcat logs (localhost_access_log). By analysing the log, I can get the download statistics based on IP or country over a period os time.

   Much appreciated.

Cheers,
Kayne.

**Comment by asawariS** [comment]
Hi @spahgnum. The tricky part of creating some of these example is getting hold of a good sample dataset. Would you have a sample Tomcat logs dataset handy that we could build out an example for?

Thanks!

**Comment by markwalkom** [comment]
G'Day @spahgnum, if you get hold of some logs we'd be happy to add these!
In the meantime we will close this one off :)
