### ISSUE TITLE
Twitter Example: Kibana Dashboard can't be imported

### ISSUE THREAD

**Issue by xinity** [elastic/examples#46]
hi,

Using Twitter Example, i've tried to import the twitter_kibana.json , but it failed :(
kibana says: Saved Objects: The file could not be processed.

using kibana Version: 4.1.1 

any clues maybe ?

thanks for your help

**Comment by xinity** [comment]
nevermind, issue on my side :(

**Comment by xeqtrspawn** [comment]
hi @xinity - Can you please let me know what was the issue? I am facing same problem here with 4.1.2, but not able to figure out.
