### ISSUE TITLE
Error when running nyc_collision_logstash.conf

### ISSUE THREAD

**Issue by imazevedo** [elastic/examples#55]
Dear, I am totally new to ELK and experimeting with your example.

Although, I´m facing this issue when i run nyc_collision_logstash.conf. I noticed that many fields are "nil" in the logs.

Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}
Ruby exception occurred: comparison of NilClass with String failed {:level=>:error}

**Comment by asawariS** [comment]
What version are you running?

**Comment by gingerwizard** [comment]
This should be resolved in the latest release.
