### ISSUE TITLE
What's the user name and password for the demo of virtual Box 

### ISSUE THREAD

**Issue by googleman2014** [elastic/examples#8]
Guys,
Please let me know the user name and password for the demo of virtual Box.

**Comment by peterskim12** [comment]
After Vagrant provisions the Virtual Box VM, in order to get shell access, you run 'vagrant ssh'. This will SSH you into the VM as the 'vagrant' user. The vagrant user can switch to the 'root' user by running 'sudo su -'.

**Comment by asawariS** [comment]
All examples have been updated to simplify the download and trial process. Closing this out since the updated examples don't use Vagrant / Virtual box. 

@googleman2014 - feel free to give the new versions a try and let us know how it goes.
