### ISSUE TITLE
snapshot restore error killed es process

### ISSUE THREAD

**Issue by zcola** [elastic/examples#9]
es version 1.4.4

When I execute 

`curl -XPOST "localhost: 9200 / _snapshot / usfec / 1 / _restore`

es the process will kill
```
[2015-03-04 11:02:02,500][INFO ][cluster.metadata         ] [node@elk-node01-6000] closing indices [[usfec_indiv_contrib]]
[2015-03-04 11:02:23,143][WARN ][cluster.metadata         ] [node@elk-node01-6000] [usfec_indiv_contrib] re-syncing mappings with cluster state for types [[indiv_contrib]]
Killed
```

**Comment by peterskim12** [comment]
Hi, thanks for the feedback. Does the elasticsearch instance actually die or just the restore process? If it is the elasticsearch instance that's dying, do you have sufficient memory/disk on the machine? This is a fairly sizable index, at least relative to what many people try to run on their laptops.

**Comment by zcola** [comment]
Hi, elasticsearch instance killed not  restore process，Part of the data has been restored to the  elasticsearch instance, I was running in a virtual machine, later I tune performance testing on a large machine instances

**Comment by MarxDimitri** [comment]
So did you have enough storage?

**Comment by asawariS** [comment]
Closing this out for now. Feel free to reopen if you are still running into this issue.
